### PR TITLE
CP-12510: Add friendly error name for VM_HOST_INCOMPATIBLE_VIRTUAL_HA…

### PR DESCRIPTION
**Pull request by MihaelaStoica**
…RDWARE_PLATFORM_VERSION

Signed-off-by: Mihaela Stoica <mihaela.stoica@citrix.com>

### CODE REVIEW

**Comment by thomassa** [comment]
The corresponding string in `datamodel.ml` is "You attempted to run a VM on a host that cannot provide the VM's required Virtual Hardware Platform version."

A VM has one version, and a host has a list of versions that it can offer. The error is raised if the VM's version is not in the host's list of versions.

Therefore a message that mentions "**the** Virtual Hardware Platform version of [a] host" could be misleading.

**Comment by stephen-turner** [comment]
Do any hosts have two versions in practice, in Dundee or earlier? We like to give the simplest possible error message.

**Comment by thomassa** [comment]
Yes. Dundee has three. Cream has two.

**Comment by stephen-turner** [comment]
I was going to suggest just changing "version" to "versions", but really it's the VM that has a virtual hardware platform, not the host. Maybe something like
  "The VM's Virtual Hardware Platform version is incompatible with this host."

**Comment by thomassa** [comment]
Seems reasonable to me.

**Comment by MihaelaStoica** [comment]
I've changed it to Stephen's suggestion, "The VM's Virtual Hardware Platform version is incompatible with this host."

**Pull request merged**
