### PR TITLE
Various fixes - inlcudes CP-32780, CP-29452, CA-75634, CA-280976, CA-333394)

### PR DESCRIPTION
**Pull request by kc284**

### CODE REVIEW

**Comment by psafont** [comment]
Travis fails because the xen-api uses ocaml 4.08 while travis is configured to run on 4.07, see https://github.com/xapi-project/xen-api-sdk/pull/167

**Comment by edwintorok** [comment]
Can you merge from master to get the CI fix?

**Comment by kc284** [comment]
@MihaelaStoica the C# SDK changes can be seen at https://github.com/kc284/xenadmin/commit/b0c65b2aeb68955b06aba06c5ba017ad3f8b76aa

**Comment by lindig** [comment]
is this ready to be merged together with the RPM spec file changes?

**Comment by kc284** [comment]
Not yet, it needs to be reviewed by @MihaelaStoica first.

**Pull request merged**
